Auto notify tuleap about current build status
jenkinsci/tuleap-git-branch-source-plugin pull request #195
Opened 2021-03-26 09:43 UTC by gorkat

part of: [story #18320](https://tuleap.net/plugins/tracker/?aid=18320) native support of pull requests in tuleap branch source jenkins plugin

## How to test

### Setup
1. First, checkout the last version of tuleap-api-plugin
2. run `mvn install` in this repository
3. Open your IDE, open the tuleap-git-branch-source-plugin
4. Edit pom.xml and replace the version of tuleap-api-plugin with the
  snapshot version built at step 2
5. Refresh the dependencies
6. Now run the plugin

### Testing

1. Go to a repository of your choice on your Tuleap instance
2. make a pullrequest containing a Jenkinsfile like this:

```
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh "sleep 10s"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
```
3. Open the pullrequest UI -> CI status: Unknown

4. Go to your repository on Jenkins and click the [Scan multibranch
   pipeline now]

5. Once the build is started, refresh the PR UI. You should see CI
   status: Pending

6. Once the build is complete, refresh the UI once again -> CI Status:
   success

2021-03-31 16:20 UTC, Erwyn requested changes

2021-03-31 16:22 UTC, Erwyn commented
You will need to put tuleap-api to version `2.2.0` in the `pom.xml` and push it here. I can't do it for you as it is on your forked repository sadly.

2021-03-31 16:23 UTC, Erwyn requested changes
You will need to put tuleap-api to version `2.2.0` in the `pom.xml` and push it here. I sadly can't do it for you as it is on your forked repository.

2021-03-31 17:13 UTC, gorkat commented on src/main/java/org/jenkinsci/plugins/tuleap_git_branch_source/TuleapSCMSource.java
> +    public TuleapAccessToken getCredentials() {
I agree, I'll see what can be done for this point :)

2021-04-06 08:34 UTC, gorkat commented on src/main/java/org/jenkinsci/plugins/tuleap_git_branch_source/TuleapSCMSource.java
> +    public TuleapAccessToken getCredentials() {
done

2021-04-12 18:19 UTC, merged